[connections.snowflake]
account = "<your_account>"
user = "<your_user>"
password = "<your_password>"
role = "<your_role>"
warehouse = "<your_warehouse>"
database = "<your_database>"
schema = "<your_schema>"